services:
  postgres:
    image: postgres:15-alpine
    container_name: groww-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: groww_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: groww-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: